# Generated by Django 5.2.1 on 2025-05-30 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.CharField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificación', models.DateTimeField(auto_now_add=True)),
                ('autor_uid', models.CharField()),
                ('autor_nombre', models.CharField(max_length=255)),
                ('autor_foto_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_uid', models.CharField()),
                ('emoji', models.CharField(choices=[('like', 'me gusta'), ('wow', 'asombro'), ('love', 'me encanta')], max_length=20)),
                ('fecha_reaccion', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='appdevug.tutorial')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'unique_together': {('usuario_uid', 'tutorial', 'emoji')},
            },
        ),
    ]
